{% set name = "pymetalink" %}
{% set version = "6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9d172a5b951ce418ceca61259c8c6a370be8798c27df02ba7dd20ae8a76c9be

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - metalink

about:
  home: https://github.com/metalink-dev/pymetalink
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: pyMetalink is a library for python to support advanced download features
  dev_url: https://github.com/metalink-dev/pymetalink

extra:
  recipe-maintainers:
    - Zeitsperre
    - cehbrecht
