{% set name = "pymetalink" %}
{% set version = "6.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e9090b9a889825abf33ccc5239c1a1cc0bca4c55ff57025b7bbf5555c334d79

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - poetry >=1.0.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - metalink

about:
  home: https://github.com/metalink-dev/pymetalink
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: pyMetalink is a library for python to support advanced download features
  dev_url: https://github.com/metalink-dev/pymetalink

extra:
  recipe-maintainers:
    - Zeitsperre
    - cehbrecht
