{% set name = "pymetalink" %}
{% set version = "6.5.3" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a9dbc33279b295c473aec1193403d34af2dc6a5e085a27f62216672965e10cf2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - metalink
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/metalink-dev/pymetalink
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: pyMetalink is a library for python to support advanced download features
  dev_url: https://github.com/metalink-dev/pymetalink

extra:
  recipe-maintainers:
    - Zeitsperre
    - cehbrecht
